### ISSUE TITLE
Missing sqrt in the paper Eq.5 re: model.py#L118 ?

### ISSUE THREAD

**Issue by guicho271828** [orybkin/sigma-vae-pytorch#1]
https://github.com/orybkin/sigma-vae-pytorch/blob/master/model.py#L118
This sqrt does not exist in the paper.

**Comment by guicho271828** [comment]
It feels this is the case where the paper is wrong. Eq 5 should be RMSE
(|x-x'|^2 / 2 s^2 + ln s)' = |x-x'|^2/2 (-2)/s^3 + 1/s = 0
|x-x'|^2 = s^2
s*=sqrt(MSE(x,x'))

**Comment by orybkin** [comment]
You are right! That's a typo in the paper, sorry about that. The paper should have \sigma^2 in eq (5), i.e. the variance is the MSE and the standard deviation is the RMSE. Thanks for catching this, will update the paper! Do let me know if you have any other issues with sigma-VAE as well.

**Comment by guicho271828** [comment]
This is unrelated, but wonder if it makes sense to stopping the gradient to sigma.
(this is a hunch)

**Comment by orybkin** [comment]
This is a good point. I tried this, and I noticed it may help stability sometimes, but generally did not have a significant effect since the shared sigma-VAE didn't suffer from instability in my experiments.
