### ISSUE TITLE
Some possible minor errors

### ISSUE THREAD

**Issue by UtrlaSeven** [orybkin/sigma-vae-pytorch#11]
1. Is the input variable name used incorrectly in gaussian_nll()? mu should be x_hat
2. In gaussian_nll(), should it be torch.pow((x-mu),2)/log_sigma.exp?

by the way, this is a great and inspiring piece of work and I look forward to your answer.

**Comment by orybkin** [comment]
1. the variable is called mu because it is the mean of the predicted distribution
2. no you divide by sigma squared as in my code, see https://en.wikipedia.org/wiki/Normal_distribution
