### ISSUE TITLE
Which torch and torchvision version did you use?

### ISSUE THREAD

**Issue by cwallenwein** [orybkin/sigma-vae-pytorch#2]
Hi, I can't run the notebook. Could you please provide the versions for torch and torchvision to allow me to run the notebook? Thank you very much :)

**Comment by cwallenwein** [comment]
Okay, just found it out. You need to 
`!pip install torch==1.4.0`
`!pip install torchvision==0.5.0`
to get it to work

**Comment by orybkin** [comment]
Thanks for spotting this! I believe I used the latest version at the time, which I guess is a bit dated now.
