### ISSUE TITLE
Negative loss

### ISSUE THREAD

**Issue by feiyuvl** [orybkin/sigma-vae-pytorch#4]
hi，when using sigma-vae, loss will decrease to negative value. Is that normal?

**Comment by orybkin** [comment]
Yes, this is expected. Negative loss means your density is more than 1,
which is perfecty possible for continuous distributions.

**Comment by feiyuvl** [comment]
Thank you, but how to judge the model convergence  if we don't have a low bound for loss?

**Comment by orybkin** [comment]
With continuous decoders, it is usually hard to tell what is the optimal
ELBO value for a particular dataset (unless you constructed it by hand and
actually know its entropy). Regarding your question though, you would judge
the model convergence by seeing if the loss is still decreasing. It is
often useful to separately plot the L2 image reconstruction error to
evaluate the decoder convergence separately from the sigma convergence.
This is not necessary with optimal sigma-VAE, where these two are the same.
