### ISSUE TITLE
Pytorch Coalb 

### ISSUE THREAD

**Issue by adityabantwal** [orybkin/sigma-vae-pytorch#5]
Hi, 
The pytorch colab notebook is showing an error.

**Comment by orybkin** [comment]
Can't verify right now, but likely because of this: https://github.com/orybkin/sigma-vae-pytorch/issues/2.

**Comment by adityabantwal** [comment]
Thanks, will check.

**Comment by orybkin** [comment]
Per Aditya's message in another thread
> The colab is working fine with pytorch 1.4
