### ISSUE TITLE
I could not recreate the result reported in Simple and Effective VAE Training with Calibrated Decoders paper

### ISSUE THREAD

**Issue by MAXzwq1998** [orybkin/sigma-vae-pytorch#7]
I ran the command: **python train_vae.py --log_dir optimal_sigma_vae --model optimal_sigma_vae**
and **generate 10000 pictures** with the trained optimal_sigma_vae model
I calculate the FID score with the SVNH dataset using the **pytorch-fid** port, but the FID score is just 44.79.
However, the FID score reported in your paper **Simple and Effective VAE Training with Calibrated Decoders** is 27.25.
I want to know if the code released is different from the code you use in your paper?
I will be grateful if you could help me to recreate your result. Thank you!

**Comment by orybkin** [comment]
Hi, which parameters did you use to compute FID? Unfortunately the scores are parameter and implementation specific so it's easy to compare incorrectly. Were you able to replicate the log-likelihood numbers?

**Comment by orybkin** [comment]
Closing until further discussion
