### ISSUE TITLE
Issues on implementing CIFAR-10 VAEs

### ISSUE THREAD

**Issue by jmyoon1** [orybkin/sigma-vae-pytorch#8]
Hi, I'm interested in your paper on calibrating the decoder likelihood.
As you mentioned in the paper, the CIFAR-10 VAE requires a more complex architecture.
If possible, can you give us a guidance that which implementation (or repo if possible) is appropriate to generate high-quality  CIFAR-10 images?

**Comment by orybkin** [comment]
Hi, these days, I would just use https://github.com/NVlabs/NVAE or https://github.com/openai/vdvae, which were both released shortly after σ-VAE. I didn't put the σ-VAE repo up mostly for that reason - it's a bit outdated on CIFAR. However, following the paper (or the commit history in this repo) you can very easily implement σ-VAE on top NVAE/VDVAE, should really be a couple of easy lines.

**Comment by jmyoon1** [comment]
I see that NVAE seems like the current SoTA VAE that works for CIFAR-10 dataset. I already added sigma-VAE into my private VAE implementation since it can be easily done by plug-in, and am planning to backbone NVAE as the architecture. Thank you.

**Comment by orybkin** [comment]
Great! Closing this for now then.
